version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      - UVICORN_WORKERS=1

  web:
    image: nginx:alpine
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./flutter_app/build/web:/usr/share/nginx/html:ro
    restart: unless-stopped



