name: flutter_app
description: Demo Flutter app for article browsing and sentiment analysis
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  provider: ^6.1.2
  hive: ^2.2.3
  fl_chart: ^0.66.2
  speech_to_text: ^7.3.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sample.json
